name: Oracle Cloud Autocreate
on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  launch-instance:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install OCI CLI
        run: |
          pip install oci-cli
          mkdir -p ~/.oci
          echo "[DEFAULT]" > ~/.oci/config
          echo "user=${{ secrets.OCI_USER_OCID }}" >> ~/.oci/config
          echo "fingerprint=${{ secrets.OCI_FINGERPRINT }}" >> ~/.oci/config
          echo "tenancy=${{ secrets.OCI_TENANCY_OCID }}" >> ~/.oci/config
          echo "region=${{ secrets.OCI_REGION }}" >> ~/.oci/config
          echo "key_file=~/.oci/key.pem" >> ~/.oci/config
          echo "${{ secrets.OCI_API_KEY }}" > ~/.oci/config_key.pem
          # Limpiar posibles espacios o formatos de la llave
          tr -d '\r' < ~/.config_key.pem > ~/.oci/key.pem
          chmod 600 ~/.oci/key.pem

      - name: Attempt to Create Instance
        run: |
          oci compute instance launch \
          --availability-domain "${{ secrets.OCI_AD }}" \
          --compartment-id "${{ secrets.OCI_COMPARTMENT_ID }}" \
          --shape VM.Standard.A1.Flex \
          --shape-config '{"ocpus":4,"memoryInGBs":24}' \
          --image-id "${{ secrets.OCI_IMAGE_ID }}" \
          --subnet-id "${{ secrets.OCI_SUBNET_ID }}" \
          --assign-public-ip true
